### ISSUE TITLE
Exporting Other Workout Types

### ISSUE THREAD

**Issue by markwk** [piscoTech/Workout#1]
Hi, looked at your iOS app and it's a great start. Would love to see it develop. 

What would it take to add option to export non-running workouts? Specifically I log my lifting workouts and workup sessions into Apple Health and looking at a tool to help me export these workouts so I can better visualize and analyze.

**Comment by piscoTech** [comment]
I don't know how lifting workout are stored inside the Health app but it will probably need to refactor the `Workout` class to be a protocol or an "abstract" one and create a subclass for each type of workout to allow different data loading mechanisms, maybe similar ones can be handled with the same class. Then the workout view must be updated to allow custom row for workout specific data and allow the main view to load all supported workouts.

PS: I would be interested in which app you use to store your lifting workouts

**Comment by markwk** [comment]
@piscoTech Missed the notifications on this. Thanks for getting back so fast. 

I'm curious if we could come up with a simple non-running export for workout types that would simply cover the essentials of an export: 

1. name of event type
2. date start
3. duration
4. (if logged) heart rate

PS -- I used Fitbod for tracking my lifting and use Sworkit for bodyweight workouts.  Neither are obviously logging the individual lifts to

**Comment by piscoTech** [comment]
The `Workout` class currently stores the raw `HKWorkout` and exposes via computed properties some data and inside the init executes some queries on the HealthStore to retrieves additional data for steps, heart rate and distance (to compute minute by minute pace/speed, total is accessible via `HKWorkout`).

We can use `Workout` for basic workouts without additional details (lifting and bodyweight should use this class if I understood correctly) and then create a subclass for running/walking workout that load additional data. `Workout` will hold the raw `HKWorkout` and expose:
- `var startDate: Date`
- `var endDate: Date`
- `var duration: TimeInterval`
- `var totalDistance: Double?`
- `var pace: TimeInterval?`

as currently implemented and maybe add (but can always be done later when a workout needs the speed and not the pace)

- `var speed: Double? // in km/h`

To load additional data we can use a private array to store a list of `HKQuery` to be executed so the base class could add one to load heart data and `RunningWorkout` subclass one to load steps and one to get detailed distance data and then execute them in a similar way to now, maybe should be who initialise the workout to call a method to do so.
`private(set) var details: [WorkoutMinute]` will remain in the base class and become optional with a method to initialise it as done [here](https://github.com/piscoTech/Workout/blob/97e3727b51174a226e21f56ef70e2e24554bdfc4/Workout/Workout.swift#L73) and as `RunningWorkout` will use the details it will invoke this method.
The callback for the heart data query will remain almost identical always adding values to `private var heartData: [Double]` and if `details` is not `nil` it'll also add it there.

To correctly load the appropriate class `Workout` will have a factory method that based on the `HKWorkout` type will load the appropriate subclass.

For now I came up with this, should be pretty simple to split the code in two classes without modifying too much. What do you think?

**Comment by standel** [comment]
Hi !
I have a similar use case. I do use your app to export data from Health app for running workouts (and pretty happy with it, thanks! :)).
I am however unable to export data from my swimming workouts. I am logging the swimming activity with the workout app of my apple watch.
Would your improvement be enough to support swimming workouts as well?

**Comment by piscoTech** [comment]
Based on what I can see in the Health app a swimming workout but should be pretty similar to a running one but with strokes instead of steps, based on what I previously proposed we need to add a `SwimmingWorkout` class that extends `Workout` that adds two query: one for swimming distance and one for strokes.

`WorkoutMinute` needs to be modified to save arbitrary data so we leave heart data as is as we need an average and add `private(set) var data: [HKQuantityTypeIdentifier: Double]` to save cumulative data such as distance, steps and strokes using a function such as [this](https://github.com/piscoTech/Workout/blob/97e3727b51174a226e21f56ef70e2e24554bdfc4/Workout/WorkoutMinute.swift#L73) that also accept what data it is and create a new entry in the dictionary or add the value the the existing one as appropriate.
Then `var pace: TimeInterval` and `var totalDistance: Double` will be modified to be optional and to try load first running distance and then swimming distance before returning `nil`, we can also add the speed.

For exporting it could be all done in `Workout` always generating `genaralData.csv` and if `private(set) var details: [WorkoutMinute]` is non-`nil` `details.csv` will be also generated, every specifying class can than specify what to extract from `WorkoutMinute.data`.

**Comment by markwk** [comment]
@piscoTech Abstracting it to a general workout class and then extending it for different options makes sense. 

Here is the full list of activity types: https://developer.apple.com/reference/healthkit/hkworkoutactivitytype. It seems like the export should support all. Some will have extended data and some will only have the start, end and duration as well as they type.

**Comment by piscoTech** [comment]
We should be able to extend this system easily with a subclass for each workout if they need additional data, and if workouts are similar they can share the same class or add Workout subclass for the common part and subclass this for specific data.

I will write a draft this weekend unless you already started.

**Comment by piscoTech** [comment]
@markwk @standel can you please review the draft for supporting multiple workout types?
