### ISSUE TITLE
Error with Workout Type: Preparation and Recovery

### ISSUE THREAD

**Issue by markwk** [piscoTech/Workout#4]
New updates look great and glad to see all my workout types now. Unfortunately export and viewing individual items for "Preparation and Recovery" causes the app to die. I log my stretching sessions via this workout type. Not sure the cause. Tell me if you need more documentation to reproduce.

**Comment by piscoTech** [comment]
I've tried manually creating a workout of that type from the Health app but the app was able to view and export it correctly. Do you record it manually or via an app, if the latter do you know if it add additional data to the workout?

I've received some crash reports from Apple, I'll try to see if they are relevant to your issue, if you haven't already opt-in can you enable sharing data with developer to make sure I receive a crashlog?

**Comment by piscoTech** [comment]
@markwk Can you post a screenshot of the workout details from inside the Health app?

**Comment by markwk** [comment]
@piscoTech I log these via Workflow app. I'll check and try to send you more intel.

**Comment by markwk** [comment]
Here are a couple screenshots: 

http://imgur.com/a/pULbl
http://imgur.com/a/LhDvz

**Comment by piscoTech** [comment]
Unfortunately they're not helpful, the crash seems to happen [here](https://github.com/piscoTech/MBLibrary/blob/v1.0.3(4)/Shared/TimeInterval.swift#L14) so it seems to be an overflowing error when converting from `TimeInterval` aka `Double` to `Int` but that's strange in your case, you seems to have no distance linked to the workout.

In any case I have some ideas in order to fix it but I'm still unable to reproduce this bug. Can you test it yourself with the pull request I'll open shortly or become a beta tester to test the release? (If the latter you direct message me on [Twitter](https://twitter.com/piscoTech) or on [my site](http://www.marcoboschi.altervista.org/contatti.php?lang=en) specifying the email of your Apple ID so I can invite you)

**Comment by piscoTech** [comment]
I was able to replicate the bug myself, it was caused by distance always being defined even for workout not distance related, causing a division by zero.

@markwk Expect an update soon that will fix the problem
